### ISSUE TITLE
Cannot access any class component inside `afterChange` event handler

### ISSUE THREAD

**Issue by abhishekb91** [handsontable/angular-handsontable#117]
### Description

The event handler for `afterChange` can't access any of the class properties or methods. 
Ideally, it should access any of the properties with `this.PROPERTY_NAME`, however, it gives the undefined error for the property.

### Steps to reproduce

1. Update any cell value and let hot run `afterChange` event
2. Check the console for the error

### Demo

https://stackblitz.com/edit/handsontable-angular-q2uxlu?file=app%2Fapp.component.ts

### Your environment
* Angular version: 6.1.2
* Handsontable version: ^5.0.2
* Wrapper version: ^2.0.0
* Browser Name and version: Google Chrome, v 69.0.3497.100
* Operating System: Windows 10

**Comment by AMBudnik** [comment]
Hi @abhishekb91 

it works fine if you convert it to an arrow function https://stackblitz.com/edit/handsontable-angular-qcgbrq?file=app/app.component.ts

**Comment by abhishekb91** [comment]
Thanks, @AMBudnik for the quick reply. It works with arrow function. But could you tell me why would it work just fine with arrow function and not with the normal function? I mean, what is causing it to break in normal function and not in arrow function

**Comment by wojciechczerniak** [comment]
It's a part of Javascript spec. Depending how or where you execute the function you can change `this` context. Since ES5 there is `.bind()` method to bind the context or an arrow function  introduced in ES6  that has `this` context already binded and immutable. 

Since it's a callback function it will be passed deep into the wrapper and Handsontable itself. A lot can happen there. Bind the function (with an arrow function) and be sure that your `this` context is the one you expect.
